// Code generated by mockery v2.52.4. DO NOT EDIT.

package tag

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	tag "github.com/radityacandra/go-cms/api/tag"
)

// MockServerInterface is an autogenerated mock type for the ServerInterface type
type MockServerInterface struct {
	mock.Mock
}

type MockServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerInterface) EXPECT() *MockServerInterface_Expecter {
	return &MockServerInterface_Expecter{mock: &_m.Mock}
}

// TagCreatePost provides a mock function with given fields: ctx
func (_m *MockServerInterface) TagCreatePost(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TagCreatePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerInterface_TagCreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagCreatePost'
type MockServerInterface_TagCreatePost_Call struct {
	*mock.Call
}

// TagCreatePost is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockServerInterface_Expecter) TagCreatePost(ctx interface{}) *MockServerInterface_TagCreatePost_Call {
	return &MockServerInterface_TagCreatePost_Call{Call: _e.mock.On("TagCreatePost", ctx)}
}

func (_c *MockServerInterface_TagCreatePost_Call) Run(run func(ctx echo.Context)) *MockServerInterface_TagCreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockServerInterface_TagCreatePost_Call) Return(_a0 error) *MockServerInterface_TagCreatePost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerInterface_TagCreatePost_Call) RunAndReturn(run func(echo.Context) error) *MockServerInterface_TagCreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// TagListGet provides a mock function with given fields: ctx, params
func (_m *MockServerInterface) TagListGet(ctx echo.Context, params tag.TagListGetParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for TagListGet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, tag.TagListGetParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerInterface_TagListGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagListGet'
type MockServerInterface_TagListGet_Call struct {
	*mock.Call
}

// TagListGet is a helper method to define mock.On call
//   - ctx echo.Context
//   - params tag.TagListGetParams
func (_e *MockServerInterface_Expecter) TagListGet(ctx interface{}, params interface{}) *MockServerInterface_TagListGet_Call {
	return &MockServerInterface_TagListGet_Call{Call: _e.mock.On("TagListGet", ctx, params)}
}

func (_c *MockServerInterface_TagListGet_Call) Run(run func(ctx echo.Context, params tag.TagListGetParams)) *MockServerInterface_TagListGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(tag.TagListGetParams))
	})
	return _c
}

func (_c *MockServerInterface_TagListGet_Call) Return(_a0 error) *MockServerInterface_TagListGet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerInterface_TagListGet_Call) RunAndReturn(run func(echo.Context, tag.TagListGetParams) error) *MockServerInterface_TagListGet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerInterface creates a new instance of MockServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerInterface {
	mock := &MockServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
