// Code generated by mockery v2.52.4. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/radityacandra/go-cms/internal/application/user/types"
)

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// AssignRole provides a mock function with given fields: ctx, userId, roleName
func (_m *MockIService) AssignRole(ctx context.Context, userId string, roleName string) error {
	ret := _m.Called(ctx, userId, roleName)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userId, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type MockIService_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - roleName string
func (_e *MockIService_Expecter) AssignRole(ctx interface{}, userId interface{}, roleName interface{}) *MockIService_AssignRole_Call {
	return &MockIService_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, userId, roleName)}
}

func (_c *MockIService_AssignRole_Call) Run(run func(ctx context.Context, userId string, roleName string)) *MockIService_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIService_AssignRole_Call) Return(_a0 error) *MockIService_AssignRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_AssignRole_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIService_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// DetailUser provides a mock function with given fields: ctx, userId
func (_m *MockIService) DetailUser(ctx context.Context, userId string) (types.DetailUserOutput, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DetailUser")
	}

	var r0 types.DetailUserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (types.DetailUserOutput, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) types.DetailUserOutput); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Get(0).(types.DetailUserOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_DetailUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetailUser'
type MockIService_DetailUser_Call struct {
	*mock.Call
}

// DetailUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockIService_Expecter) DetailUser(ctx interface{}, userId interface{}) *MockIService_DetailUser_Call {
	return &MockIService_DetailUser_Call{Call: _e.mock.On("DetailUser", ctx, userId)}
}

func (_c *MockIService_DetailUser_Call) Run(run func(ctx context.Context, userId string)) *MockIService_DetailUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIService_DetailUser_Call) Return(_a0 types.DetailUserOutput, _a1 error) *MockIService_DetailUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_DetailUser_Call) RunAndReturn(run func(context.Context, string) (types.DetailUserOutput, error)) *MockIService_DetailUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, input
func (_m *MockIService) RegisterUser(ctx context.Context, input types.RegisterUserInput) (types.RegisterUserOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 types.RegisterUserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RegisterUserInput) (types.RegisterUserOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RegisterUserInput) types.RegisterUserOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(types.RegisterUserOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RegisterUserInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockIService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.RegisterUserInput
func (_e *MockIService_Expecter) RegisterUser(ctx interface{}, input interface{}) *MockIService_RegisterUser_Call {
	return &MockIService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, input)}
}

func (_c *MockIService_RegisterUser_Call) Run(run func(ctx context.Context, input types.RegisterUserInput)) *MockIService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RegisterUserInput))
	})
	return _c
}

func (_c *MockIService_RegisterUser_Call) Return(_a0 types.RegisterUserOutput, _a1 error) *MockIService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_RegisterUser_Call) RunAndReturn(run func(context.Context, types.RegisterUserInput) (types.RegisterUserOutput, error)) *MockIService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
