// Code generated by mockery v2.52.4. DO NOT EDIT.

package repository

import (
	context "context"

	model "github.com/radityacandra/go-cms/internal/application/tag/model"
	mock "github.com/stretchr/testify/mock"

	types "github.com/radityacandra/go-cms/internal/application/tag/types"
)

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// CreateTag provides a mock function with given fields: ctx, input
func (_m *MockIRepository) CreateTag(ctx context.Context, input model.Tag) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Tag) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockIRepository_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.Tag
func (_e *MockIRepository_Expecter) CreateTag(ctx interface{}, input interface{}) *MockIRepository_CreateTag_Call {
	return &MockIRepository_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, input)}
}

func (_c *MockIRepository_CreateTag_Call) Run(run func(ctx context.Context, input model.Tag)) *MockIRepository_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Tag))
	})
	return _c
}

func (_c *MockIRepository_CreateTag_Call) Return(_a0 error) *MockIRepository_CreateTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_CreateTag_Call) RunAndReturn(run func(context.Context, model.Tag) error) *MockIRepository_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// FindTagById provides a mock function with given fields: ctx, tagId
func (_m *MockIRepository) FindTagById(ctx context.Context, tagId string) (*model.Tag, error) {
	ret := _m.Called(ctx, tagId)

	if len(ret) == 0 {
		panic("no return value specified for FindTagById")
	}

	var r0 *model.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Tag, error)); ok {
		return rf(ctx, tagId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Tag); ok {
		r0 = rf(ctx, tagId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tagId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_FindTagById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTagById'
type MockIRepository_FindTagById_Call struct {
	*mock.Call
}

// FindTagById is a helper method to define mock.On call
//   - ctx context.Context
//   - tagId string
func (_e *MockIRepository_Expecter) FindTagById(ctx interface{}, tagId interface{}) *MockIRepository_FindTagById_Call {
	return &MockIRepository_FindTagById_Call{Call: _e.mock.On("FindTagById", ctx, tagId)}
}

func (_c *MockIRepository_FindTagById_Call) Run(run func(ctx context.Context, tagId string)) *MockIRepository_FindTagById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRepository_FindTagById_Call) Return(_a0 *model.Tag, _a1 error) *MockIRepository_FindTagById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_FindTagById_Call) RunAndReturn(run func(context.Context, string) (*model.Tag, error)) *MockIRepository_FindTagById_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockIRepository) ListAll(ctx context.Context) (types.ListActiveTagOutput, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 types.ListActiveTagOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.ListActiveTagOutput, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.ListActiveTagOutput); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.ListActiveTagOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockIRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRepository_Expecter) ListAll(ctx interface{}) *MockIRepository_ListAll_Call {
	return &MockIRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockIRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockIRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRepository_ListAll_Call) Return(_a0 types.ListActiveTagOutput, _a1 error) *MockIRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_ListAll_Call) RunAndReturn(run func(context.Context) (types.ListActiveTagOutput, error)) *MockIRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListTag provides a mock function with given fields: ctx, input
func (_m *MockIRepository) ListTag(ctx context.Context, input types.ListTagInput) (types.ListTagOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListTag")
	}

	var r0 types.ListTagOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ListTagInput) (types.ListTagOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ListTagInput) types.ListTagOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(types.ListTagOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ListTagInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_ListTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTag'
type MockIRepository_ListTag_Call struct {
	*mock.Call
}

// ListTag is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.ListTagInput
func (_e *MockIRepository_Expecter) ListTag(ctx interface{}, input interface{}) *MockIRepository_ListTag_Call {
	return &MockIRepository_ListTag_Call{Call: _e.mock.On("ListTag", ctx, input)}
}

func (_c *MockIRepository_ListTag_Call) Run(run func(ctx context.Context, input types.ListTagInput)) *MockIRepository_ListTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ListTagInput))
	})
	return _c
}

func (_c *MockIRepository_ListTag_Call) Return(_a0 types.ListTagOutput, _a1 error) *MockIRepository_ListTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_ListTag_Call) RunAndReturn(run func(context.Context, types.ListTagInput) (types.ListTagOutput, error)) *MockIRepository_ListTag_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTag provides a mock function with given fields: ctx, input
func (_m *MockIRepository) UpdateTag(ctx context.Context, input model.Tag) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Tag) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_UpdateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTag'
type MockIRepository_UpdateTag_Call struct {
	*mock.Call
}

// UpdateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.Tag
func (_e *MockIRepository_Expecter) UpdateTag(ctx interface{}, input interface{}) *MockIRepository_UpdateTag_Call {
	return &MockIRepository_UpdateTag_Call{Call: _e.mock.On("UpdateTag", ctx, input)}
}

func (_c *MockIRepository_UpdateTag_Call) Run(run func(ctx context.Context, input model.Tag)) *MockIRepository_UpdateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Tag))
	})
	return _c
}

func (_c *MockIRepository_UpdateTag_Call) Return(_a0 error) *MockIRepository_UpdateTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_UpdateTag_Call) RunAndReturn(run func(context.Context, model.Tag) error) *MockIRepository_UpdateTag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
