// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	// Password user password for authentication purpose
	Password string `json:"password" validate:"required"`

	// Username username of the user
	Username string `json:"username" validate:"required"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	// Token bearer token to be attached on any resources
	Token string `json:"token"`
}

// AuthUserInfoGetResponse defines model for AuthUserInfoGetResponse.
type AuthUserInfoGetResponse struct {
	// Scopes allowed access scopes
	Scopes []string `json:"scopes"`

	// Username username of the authenticated user
	Username string `json:"username"`
}

// DefaultErrorResponse defines model for DefaultErrorResponse.
type DefaultErrorResponse struct {
	// Error error description
	Error string `json:"error"`
}

// UserPostRequest defines model for UserPostRequest.
type UserPostRequest struct {
	// Password user password for authentication purpose
	Password string `json:"password" validate:"required"`

	// Username username of the user
	Username string `json:"username" validate:"required"`
}

// UserPostResponse defines model for UserPostResponse.
type UserPostResponse struct {
	// Id user id
	Id string `json:"id"`
}

// AuthLoginPostJSONRequestBody defines body for AuthLoginPost for application/json ContentType.
type AuthLoginPostJSONRequestBody = AuthLoginRequest

// UserPostJSONRequestBody defines body for UserPost for application/json ContentType.
type UserPostJSONRequestBody = UserPostRequest
